### ISSUE TITLE
неочевидный момент #9

### ISSUE THREAD

**Issue by maksgir** [MikhailDolinnyi/web_lab2#14]
https://github.com/MikhailDolinnyi/web_lab2/blob/86d996b6c9d3b254cd043a4f6afe1f24092a24de/src/main/java/ru/mikhail/lab2/ControllerServlet.java#L30
нпе - такая зараза, что может выпасть где угодно, а ты же её ловишь с уверенностью в том, что она упала только потому, что параметра в контексте нет. лучше самому проверить это, и кидать соответствующую ошибку только наверняка, а ловить нпе лучше в самом низу, как что-то неожиданное

**Comment by MikhailDolinnyi** [comment]
Ехала🏴‍☠️. 
Всё резолвнул, ишусы закрою
